# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 295b09d2e509d8336a7d6cce3c31227ab179af74df3f8babdcccfe207e14c82c7cffa675f82bb5dd839a35175a1cb0087c1e66d7f8f4d4f18b600de7ced32263

test:
  secret_key_base: ca268052cede6bf45f02e0fc6a400544566a3b7fd75851505e4f6c24c9937730d5e9889e5fdacf811c1915e9c172211a5be84295a1430931b257e720f7f8ba91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
